// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "StudyMethods",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "StudyMethods",
            targets: ["AppModule"],
            bundleIdentifier: "com.SebastianContreras.StudyMethods",
            teamIdentifier: "QF2R75VM2Y",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .cloud),
            accentColor: .presetColor(.red),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .education
        )
    ],
    dependencies: [
        .package(url: "https://github.com/SDWebImage/SDWebImageSwiftUI", "3.1.3"..<"4.0.0"),
        .package(url: "https://github.com/ThasianX/ElegantCalendar", "4.3.2"..<"5.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "SDWebImageSwiftUI", package: "sdwebimageswiftui"),
                .product(name: "ElegantCalendar", package: "elegantcalendar")
            ],
            path: "."
        )
    ]
)